name: Build DarcyFoam

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openfoamplus/of_v2406_centos73  # Imagem correta do OpenFOAM

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar OpenFOAM e compilar DarcyFoam
        run: |
          source /opt/OpenFOAM/OpenFOAM-v2406/etc/bashrc
          wmake
