name: Build DarcyFoam

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openfoam/openfoam:v2406  # Usa a imagem oficial do OpenFOAM

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar OpenFOAM e compilar DarcyFoam
        run: |
          source /opt/openfoam2406/etc/bashrc
          wmake
