name: Build DarcyFoam

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Adicionar repositório e instalar OpenFOAM
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y "deb http://dl.openfoam.org/ubuntu $(lsb_release -cs) main"
          curl -fsSL http://dl.openfoam.org/gpg.key | sudo tee /etc/apt/trusted.gpg.d/openfoam.asc
          sudo apt-get update
          sudo apt-get install -y openfoam2406

      - name: Compilar DarcyFoam com wmake
        run: |
          source /usr/lib/openfoam/openfoam2406/etc/bashrc
          wmake
        working-directory: ${{ github.workspace }}
