name: Build DarcyFoam

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar OpenFOAM
        run: |
          sudo apt-get update
          sudo apt-get install -y openfoam

      - name: Compilar DarcyFoam com wmake
        run: |
          source /usr/lib/openfoam/openfoam2406/etc/bashrc
          wmake
        working-directory: ${{ github.workspace }}
