name: Build DarcyFoam

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Construir a imagem Docker personalizada
        run: docker build -t openfoam-custom .

      - name: Compilar DarcyFoam
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/openfoam openfoam-custom /bin/bash -c "
            source /opt/openfoam8/etc/bashrc
            cd /home/openfoam
            wmake
          "

